wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.21.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1752884475
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 4
      - 16
      - 42
      4: 3.11.5
      5: 0.21.0
      8:
      - 2
      13: linux-x86_64
    e:
      h35q4j84simz1ebkzulxcikh3349rf2o:
        os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
        python: CPython 3.11.5
        started_at: '2025-07-19T00:21:14.724547Z'
        program: /mnt/f/maimai/train.py
        code_path: train.py
        code_path_local: train.py
        root: /mnt/f/maimai
        host: DESKTOP-1QL32VN
        executable: /mnt/f/maimai/.venv/bin/python3
        cpu_count: 2
        cpu_count_logical: 4
        gpu_type: NVIDIA GeForce RTX 3060 Laptop GPU
        gpu_count: 1
        disk:
          /:
            total: '1081101176832'
            used: '129978462208'
        memory:
          total: '10430435328'
        gpu_nvidia:
        - name: NVIDIA GeForce RTX 3060 Laptop GPU
          memory_total: '6442450944'
          architecture: Ampere
          uuid: GPU-37313938-fcb5-dec5-8f1e-95b79e1b8d95
        cuda_version: '12.5'
        writer_id: h35q4j84simz1ebkzulxcikh3349rf2o
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 1000
early_stopping_patience:
  desc: null
  value: 10
target_loss:
  desc: null
  value: 0.01
model_name:
  desc: null
  value: LSTMWithAttention
