_wandb:
    value:
        cli_version: 0.21.0
        e:
            815eoql8vaqqimaec6a73t4ubu7iume2:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "1081101176832"
                        used: "129623265280"
                email: 1187305740@qq.com
                executable: /mnt/f/maimai/.venv/bin/python3
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-37313938-fcb5-dec5-8f1e-95b79e1b8d95
                host: DESKTOP-1QL32VN
                memory:
                    total: "10430431232"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /mnt/f/maimai/train.py
                python: CPython 3.11.5
                root: /mnt/f/maimai
                startedAt: "2025-07-19T01:09:58.889269Z"
                writerId: 815eoql8vaqqimaec6a73t4ubu7iume2
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
            "4": 3.11.5
            "5": 0.21.0
            "8":
                - 2
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 32
early_stopping_patience:
    value: 10
epochs:
    value: 1000
learning_rate:
    value: 0.001
model_name:
    value: LSTMWithAttention
target_loss:
    value: 0.01
